const ActionTypes = {
    ADD_INVOICE: "ADD_INVOICE",
    FIND_INVOICES: "FIND_INVOICES",
    REQUEST_LOGIN: "REQUEST_LOGIN",
    RECEIVE_LOGIN: "RECEIVE_LOGIN",
    ERROR_LOGIN: "ERROR_LOGIN",
}

export default ActionTypes;